In [79]:
import numpy as np

class GridWorld:
    def __init__(self):
        self.action_space = [0, 1, 2, 3]
        self.action_meaning = {
            0: "UP",
            1: "DOWN",
            2: "LEFT",
            3: "RIGHT",
        }
        
        self.reward_map = np.array(
            [[0, 0, 1.0],
             [0, 0, 0],
             [0, 0.,0]]
        )
        self.reward_apple = 1.0
        self.goal_state = (0, 2)
        self.start_state = (2, 0)
        self.agent_state = self.start_state
        
        while True:
            self.row_index = np.random.randint(0, map.shape[0])
            self.col_index = np.random.randint(0, map.shape[1])
            if self.row_index == self.goal_state[0] and  self.col_index == self.goal_state[1]: # リンゴの位置はgoalの座標ではないか？
                continue
            elif self.row_index == self.start_state[0] and  self.col_index == self.start_state[1]:# リンゴの位置はstartの座標ではないか？
                continue
            else:
                break
        self.reward_map[self.row_index, self.col_index] = self.reward_apple
        
    @property
    def height(self):
        return len(self.reward_map)
        
    @property
    def width(self):
        return len(self.reward_map[0])
        
    @property
    def shape(self):
        return self.reward_map.shape
        
    def action(self):
        return self.action_space # [0, 1, 2, 3]
        
    def states(self):
        for h in range(self.height):
             for w in range(self.width):
                yield(h, w)

env = GridWorld()
print(env.height)
print(env.width)
print(env.shape)

3
3
(3, 3)


In [74]:
import numpy as np
map = np.array(
    [[0, 0, 1.0],
     [0, 0, 0],
     [0, 0.,0],
    ]
)

goal_state = (0, 2)
start_state = (2, 0)

# print(map.shape[0]) # 行の数
# print(map.shape[1]) # 列の数

# ランダムな位置を選択
while True:
    row_index = np.random.randint(0, map.shape[0]) # map.shape[0] 行数
    col_index = np.random.randint(0, map.shape[1]) # map.shape[1] 列数
    random_index = (row_index, col_index)
    print("ランダムに選んだ座標：", random_index)
    if random_index[0] == goal_state[0] and  random_index[1] == goal_state[1]:
        continue
        # print('ゴールの座標が選ばれました。座標を選び直します。')
    elif random_index[0] == start_state[0] and  random_index[1] == start_state[1]:
        continue
        # print("スタートの座標が選ばれました。座標を選び直します。")
    else:
        # print('ゴールまたはスタートの座標ではありません。ループを抜けます。')
        break
    
# ランダムな値を生成して要素に挿入
map[row_index, col_index] = 1.0

# 結果を表示
print(map)


ランダムに選んだ座標： (0, 0)
[[1. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
i = 0
# while i < 3:
#     x = np.random.randint(0, 5)
#     if x == 1:
#         print("繰り返しを終了します")
#         break
#     else:
#         print(x)
#     i += 1


# for i in range(10):
#     x = np.random.randint(0, 5)
#     if x == 1:
#         print("x = 1です。繰り返しを終了します")
#         break
#     else:
#         print(x)

a = (1, 2)
b = (1, 2)
if a[0] == b[0] and a[1] == b[1]:
    print("True")
else:
    print("False")

True
